# Generated by Django 5.1.1 on 2025-04-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_status_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='food_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
